name: Build and Push Microservices

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  discover-services:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect changed files
        id: changed-files
        run: |
          if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
            CHANGED_FILES=$(git ls-files)
          else
            CHANGED_FILES=$(git diff --name-only origin/main...HEAD)
          fi

          echo "Changed files:"
          echo "$CHANGED_FILES"

          echo "$CHANGED_FILES" > changed_files.txt

      - name: Generate dynamic matrix
        id: set-matrix
        run: |
          FULL_MATRIX=$(cat .github/config/services.json)

          BUILD_ALL=false

          if grep -E "pom.xml|docker/|.github/workflows/" changed_files.txt; then
            BUILD_ALL=true
          fi

          if [ "$BUILD_ALL" = true ]; then
            echo "Building all services..."

            MATRIX=$(echo $FULL_MATRIX | jq -c .)

          else
            FILTERED='[]'

            for SERVICE in $(echo $FULL_MATRIX | jq -c '.[]'); do

              SERVICE_NAME=$(echo $SERVICE | jq -r '.service')
              MODULE_NAME=$(echo $SERVICE | jq -r '.module')

              if grep -q "$MODULE_NAME" changed_files.txt; then
                FILTERED=$(echo $FILTERED | jq ". + [$SERVICE]")
              fi

            done

            MATRIX=$(echo $FILTERED | jq -c .)
          fi

          echo "Final matrix:"
          echo "$MATRIX"

          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  build-and-push:
    if: ${{ needs.discover-services.outputs.matrix != '[]' }}
    needs: discover-services
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        service: ${{ fromJson(needs.discover-services.outputs.matrix) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::482352877891:role/GitHubActionsECRPushRole
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build Maven module
        run: |
          ./mvnw clean package \
            -pl ${{ matrix.service.module }} \
            -am \
            -DskipTests

      - name: Build Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ matrix.service.ecr_repo }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cp ${{ matrix.service.module }}/target/*.jar .

          docker build \
            -f docker/Dockerfile \
            --build-arg ARTIFACT_NAME=$(basename *.jar .jar) \
            --build-arg EXPOSED_PORT=${{ matrix.service.port }} \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            .

      - name: Push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ matrix.service.ecr_repo }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update Kubernetes manifests
        env:
          IMAGE_TAG: ${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.INFRA_REPO_TOKEN }}

        run: |
          git clone https://x-access-token:${GITHUB_TOKEN}@github.com/petclinic-project/petclinic-infrastructure.git

          cd petclinic-infrastructure
          git checkout develop

          DEPLOYMENT_FILE=kubernetes/base/${{ matrix.service.service }}/deployment.yaml

          sed -i "s|image: .*|image: 482352877891.dkr.ecr.ap-south-1.amazonaws.com/${{ matrix.service.ecr_repo }}:${IMAGE_TAG}|g" $DEPLOYMENT_FILE

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add $DEPLOYMENT_FILE

          git commit -m "ci(cd): update ${{ matrix.service.service }} image to ${IMAGE_TAG}" || echo "No changes to commit"
          git pull --rebase origin develop

          git push origin develop
