name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  discover-services:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.services.outputs.matrix }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read services.json
        id: services
        run: |
          MATRIX=$(jq -c . .github/config/services.json)
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  build-and-push:
    needs: discover-services

    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: ${{ fromJson(needs.discover-services.outputs.matrix) }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE }}
          aws-region: ap-south-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build JAR
        run: |
          chmod +x mvnw

          ./mvnw clean package -DskipTests

          cp \
            ./${{ matrix.service.module }}/target/*.jar \
            ./${{ matrix.service.module }}.jar

      - name: Build and Push ARM64 Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          build-args: |
            ARTIFACT_NAME=${{ matrix.service.module }}
          platforms: linux/amd64
          push: true
          tags: |
            482352877891.dkr.ecr.ap-south-1.amazonaws.com/${{ matrix.service.ecr_repo }}:${{ github.sha }}
            482352877891.dkr.ecr.ap-south-1.amazonaws.com/${{ matrix.service.ecr_repo }}:latest
