name: Update Image Tags

on:
  workflow_run:
    workflows:
      - Build and Push Docker Images
    types:
      - completed

jobs:
  update-tags:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Infrastructure Repo
        uses: actions/checkout@v4
        with:
          repository: petclinic-project/petclinic-infrastructure
          ref: develop
          token: ${{ secrets.GH_PAT }}

      - name: Update Image Tags
        run: |
          for FILE in kubernetes/overlays/dev/values/*.yaml
          do
            sed -i "s|tag: .*|tag: ${GITHUB_SHA}|g" "$FILE"
            echo "Updated $FILE"
          done

      - name: Commit Changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .

          git commit -m "ci(cd): update image tags to ${GITHUB_SHA}" || echo "No changes"

          git push origin develop
